server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CarrilloYago/config-service
          skipSslValidation: true
          clone-on-start: true
eureka:
  instance:
    client:
      serviceUrl.defaultZone=http://localhost:8761/eureka/